config/routes.rb
Kwp14::Application.routes.draw do
  resources :roles
  resources :votes
  resources :users

  
  resources :topics 
  resources :administration do
    collection do
      get 'index'
      get 'encrypt'
    end
  end
  resources :comments 
  resources :users 
  resources :user_sessions 
   match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'topics#index'
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  attr_accessible :topic_id, :user_id, :value
  validates :value , presence: true

  belongs_to :topic
  belongs_to :user
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  # GET /votes/new
  # GET /votes/new.json
  def new
    @vote = Vote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vote }
    end
  end
  def create
    @vote = Vote.new(params[:vote])
    respond_to do |format|
      if @vote.save
        @vote.topic.recalculate_rating
        @vote.topic.save!
        format.html { redirect_to topics_path(:anchor => "topic_#{@vote.topic_id}"), notice: "Sie haben mit \"#{@vote.value}\" abgestimmt" }
        format.json { render json: @vote, status: :created, location: @vote }
      else
        format.html { redirect_to :back, notice: "Sie koennen keine leeren Bewertungen abgeben" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /votes/1
  # PUT /votes/1.json
  def update
    @vote = Vote.find(params[:id])

    respond_to do |format|
      if @vote.update_attributes(params[:vote])
        @vote.topic.recalculate_rating
        @vote.topic.save!
        format.html { redirect_to topics_path(:anchor => "topic_#{@vote.topic_id}"), notice: "Sie haben mit \"#{@vote.value}\" abgestimmt" }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote = Vote.find(params[:id])
    #@vote.destroy

    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 <%= f.hidden_field :topic_id %> 
 <%= f.hidden_field :user_id %> 
  <span class="field">
    <table style="text-align:center;">
      <tr>
        <td></td>
        <% (0..5).to_a.each do |n| %>
          <td> 
            <%if @old_vote  and @old_vote.value == n%>
              <%= f.radio_button :value ,n , {:checked => true }%>
            <%else%>
              <%= f.radio_button :value ,n %>
            <%end%>
          </td>
        <%end%>
        <td></td>
      </tr>
      <tr>
        <td> Unwichtig </td>
        <% (0..5).to_a.each do |n| %>
        <td> <%= n %> </td>
        <%end%>
        <td> Wichtig </td>
      </tr>
    </table>

  </span>
  <span class="actions">
    <%= f.submit  "bewerten"%>
  </span>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <tr>
    <th>User</th>
    <th>Topic</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @votes.each do |vote| %>
  <tr>
    <td><%= vote.user_id %></td>
    <td><%= vote.topic_id %></td>
    <td><%= vote.value %></td>
    <td><%= link_to 'Show', vote %></td>
    <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
    <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @vote.user_id %>
</p>

<p>
  <b>Topic:</b>
  <%= @vote.topic_id %>
</p>

<p>
  <b>Value:</b>
  <%= @vote.value %>
</p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>