config/routes.rb
Kwp14::Application.routes.draw do
  resources :roles
  resources :votes
  resources :users

  
  resources :topics 
  resources :administration do
    collection do
      get 'index'
      get 'encrypt'
    end
  end
  resources :comments 
  resources :users 
  resources :user_sessions 
   match 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'topics#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kwp14</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% unless flash.empty? %>
    <!-- 
      <script type="text/javascript">
        onload()
        {
          alert(<%=flash[:notice]%>);
        };
      </script>
    -->
  <%end%>
  <%= flash[:notice] %>
  

<script type="text/javascript">
<!--
function toggle_visibility(id) {
var e = document.getElementById(id);
if(e.style.display == 'block')
e.style.display = 'none';
else
e.style.display = 'block';
}
//-->
</script> 

  <div id="top_bar" >
    <span class="title"> KWP14 </span>
    <span class="top_bar_element"> <%= link_to 'start', topics_path(:filter=>"no", :sort => "no") %> </span>
    <span class="top_bar_element"> <%= mail_to 'kontakt@dielinke-dresden.de', "kontakt", :subject => "KWP 14" %> </span>
    <span class="top_bar_element"> <%= link_to "Neueste Kommentare", comments_path %> </span>
    <span class="top_bar_element"> <a href="#" onclick="toggle_visibility('sort_list');">sortiere</a> </span>
    <span class="top_bar_element"> <a href="#" onclick="toggle_visibility('filter_list');">filter</a> </span>
    <% if current_user %>
      <span class="top_bar_element"> <%= link_to 'log out', :logout %> </span>
    <% else %>
      <span class="top_bar_element"> <%= link_to 'log in', new_user_session_path %> </span>
      <span class="top_bar_element"> <%= link_to 'registrieren', new_user_path %> </span>
      <%end%>
      <br  />
      <div id="filter_list" style="display:none">
        <% filter_list.each do |filter| %>
        <span class="top_bar_element" > <%= link_to filter, topics_path(:filter => filter) %>  </span>
        <%end%>
      </div>
      <div id="sort_list" style="display:none">
        <% sort_list.each do |sort| %>
        <span class="top_bar_element" > <%= link_to sort, topics_path(:sort => sort) %>  </span>
        <%end%>
      </div>
  </div>


  <div id="content">
    <%= yield %>
  </div>

</body>
</html>